title: ABC Lab ELN
author: ABC Lab
logo: _static/logo.png
html:
  extra_js:
    - _static/auth.js
  favicon: _static/favicon.ico
  use_repository_button: false
  use_edit_page_button: false
  use_issues_button: false
