# _config.yml
title: "ABC Lab ELN"
author: "ABC Lab @ UMD"
logo: "_static/logo.png"
html:
  favicon: "_static/favicon.ico"
  use_edit_page_button: false
  extra_footer: |
    <p>© ABC Lab – University of Maryland</p>
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - html_admonition
    - html_image
    - linkify
    - substitution
    - tasklist
launch_buttons: {}
